name: Test collective.z3cform.datagridfield

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        plone:
          - "6.0-dev"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        id: setup
        uses: plone/setup-plone@v2.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}

      - name: Install package
        run: |
          make VENV=off install

      - name: Run Lint
        run: |
          make VENV=off lint

      - name: Install Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Start Browser
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1920x1280x24 > /dev/null 2>&1 &
          sleep 5  # make sure chromedriver and Xvfb is running

      - name: Run tests
        run: |
          make VENV=off test-ignore-warnings

      - name: Save Robotframework Log
        uses: actions/upload-artifact@v3
        # safe artifacts only for failing tests
        if: ${{ failure() }}
        with:
          name: robottest-logfiles-${{ matrix.plone }}-${{ matrix.python }}
          path: |
            test_*
            robot_*
